CREATE TABLE `companyProfiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`userId` int NOT NULL,
	`companyName` varchar(255) NOT NULL,
	`companyWebsite` varchar(500),
	`companyDescription` text,
	`industry` varchar(255),
	`products` json,
	`targetMarket` text,
	`headquarters` varchar(255),
	`estimatedSize` varchar(100),
	`keyDifferentiator` text,
	`salesStages` json,
	`avgDealSize` varchar(100),
	`avgDealCycle` varchar(100),
	`salesTeamSize` varchar(100),
	`icpIndustries` text,
	`icpCompanySize` varchar(255),
	`icpTitles` text,
	`icpPainPoints` text,
	`knowledgeBaseText` text,
	`onboardingCompleted` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `companyProfiles_id` PRIMARY KEY(`id`)
);
