import React, { createContext, useContext, useState } from "react";

export type Language = "en" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.deals": "Pipeline",
    "nav.stakeholders": "Stakeholders",
    "nav.transcripts": "Deal Room",
    "nav.knowledge": "Knowledge Base",
    "nav.ask": "Ask Meridian",
    "nav.settings": "Settings",
    "nav.signout": "Sign out",
    "nav.newDeal": "New Deal",
    // Settings page
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.account.desc": "Manage your profile and preferences",
    "settings.language": "Language & Region",
    "settings.language.desc": "Choose your preferred language",
    "settings.team": "Team",
    "settings.team.desc": "Invite colleagues and manage team access",
    "settings.displayName": "Display Name",
    "settings.email": "Email",
    "settings.save": "Save Changes",
    "settings.saved": "Changes saved",
    "settings.lang.en": "English",
    "settings.lang.zh": "中文 (Chinese)",
    "settings.invite.email": "Email address",
    "settings.invite.send": "Send Invite",
    "settings.invite.sent": "Invite sent!",
    "settings.invite.placeholder": "colleague@company.com",
    "settings.members": "Team Members",
    "settings.theme": "Appearance",
    "settings.theme.dark": "Dark",
    "settings.theme.light": "Light",
    // Dashboard
    "dashboard.greeting": "Good morning",
    "dashboard.welcome": "Welcome to Meridian. Create your first deal to get started.",
    "dashboard.attention": "Here's what needs your attention today.",
    "dashboard.totalPipeline": "Total Pipeline",
    "dashboard.predictableRevenue": "Predictable Revenue",
    "dashboard.avgConfidence": "Avg Confidence",
    "dashboard.atRiskDeals": "At Risk Deals",
    "dashboard.dealsNeedingAction": "Deals Needing Action",
    "dashboard.allDeals": "All Deals",
    "dashboard.total": "total",
    "dashboard.pipelineByStage": "Pipeline by Stage",
    // Pipeline sidebar
    "pipeline.overview": "Pipeline Overview",
    "pipeline.searchDeals": "Search deals...",
    "pipeline.noDeals": "No deals yet.",
    "pipeline.createFirst": "Create your first deal",
    "pipeline.totalPipeline": "Total Pipeline",
    "pipeline.predictableRevenue": "Predictable Revenue",
    "pipeline.newDeal": "New Deal",
    "pipeline.show": "Show Pipeline",
    "pipeline.hide": "Hide Pipeline",
    // Deal detail
    "deal.lastEdited": "last edited",
    "deal.ago": "ago",
    "deal.updateHistory": "Update Account History",
    "deal.buyingCommittee": "Buying Committee",
    "deal.accountSignals": "Account Signals",
    "deal.allInteractions": "All Interactions",
    "deal.dealStrategy": "Deal Strategy",
    "deal.dealInsight": "Deal Insight",
    "deal.winConfidence": "Win Confidence",
    "deal.analyseDeal": "Analyse deal",
    "deal.whatsHappening": "WHAT'S HAPPENING",
    "deal.keyRisks": "KEY RISKS",
    "deal.whatsNext": "WHAT'S NEXT",
    "deal.nextActions": "NEXT ACTIONS",
    "deal.noActions": "No actions yet — click + to add",
    "deal.interactions": "INTERACTIONS",
    "deal.noContact": "No contact",
    "deal.reportsTo": "Reports To",
    "deal.influences": "Influences",
    "deal.collaborates": "Collaborates",
    "deal.blocks": "Blocks",
    "deal.positive": "Positive",
    "deal.neutral": "Neutral",
    "deal.negative": "Negative",
    "deal.heat": "Heat = L14D touchpoints",
    "deal.view": "View",
    "deal.edit": "Edit",
    "deal.addInteraction": "Add interaction",
    // Stakeholder roles
    "role.champion": "Champion",
    "role.decisionMaker": "Decision Maker",
    "role.influencer": "Influencer",
    "role.blocker": "Blocker",
    "role.evaluator": "Evaluator",
    "role.endUser": "End User",
    // Stages
    "stage.discovery": "Discovery",
    "stage.demo": "Demo",
    "stage.technicalEvaluation": "Technical Evaluation",
    "stage.poc": "POC",
    "stage.negotiation": "Negotiation",
    "stage.closedWon": "Closed Won",
    "stage.closedLost": "Closed Lost",
    // Common
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.loading": "Loading...",
    "common.back": "Back",
    "common.next": "Next",
    "common.day": "Day",
    "common.lightMode": "Light mode",
    "common.darkMode": "Dark mode",
    // Onboarding
    "onboarding.step1": "Product Info",
    "onboarding.step2": "Sales Process",
    "onboarding.step3": "Define ICP",
    // DealDetail page
    "deal.loadingDeal": "Loading deal...",
    "deal.notFound": "Deal not found",
    "deal.backToDashboard": "Back to Dashboard",
    "deal.companyOverview": "Company Overview",
    "deal.happening": "Happening: ",
    "deal.next": "Next: ",
    "deal.risks": "Risks: ",
    "deal.interactionsRecorded": "interactions recorded",
    "deal.interactionRecorded": "interaction recorded",
    "deal.noInteractions": "No interactions recorded yet",
    "deal.addInteractionHint": "Click \"Add Interaction\" to log your first touchpoint",
    "deal.notesTranscript": "Notes / Transcript",
    "deal.meetingNotesPlaceholder": "Meeting notes, key decisions, action items...",
    "deal.done": "Done",
    "deal.delete": "Delete",
    "deal.participantName": "Participant name",
    "deal.noNotesYet": "No notes yet — click pencil to add",
    "deal.collapseTranscript": "Collapse Transcript",
    "deal.viewFullTranscript": "View Full Transcript",
    "deal.fullTranscript": "Full Transcript",
    "deal.fullNotes": "Full Notes",
    "deal.strategyTitle": "Deal Strategy",
    "deal.strategyDesc": "Internal strategy notes for this deal — pricing flexibility, relationship plays, competitive intel, and internal alignment. These notes inform the AI agent's recommendations.",
    "deal.addNote": "Add Note",
    "deal.noStrategyNotes": "No strategy notes yet",
    "deal.strategyEmptyHint": "Add internal context like pricing flexibility, strategic priority, or relationship plays — the AI agent will use these to tailor its recommendations.",
    "deal.addFirstNote": "Add First Strategy Note",
    "deal.strategyPlaceholder": "Describe the internal strategy, context, or constraints for this deal...",
    "deal.emptyNote": "Empty note — click pencil to add content",
    // Strategy categories
    "strategy.pricing": "Pricing Flexibility",
    "strategy.relationship": "Relationship Strategy",
    "strategy.competitive": "Competitive Intel",
    "strategy.internal": "Internal Alignment",
    "strategy.other": "Other",
    // Stakeholder profile modal
    "deal.brief": "Brief",
    "deal.profile": "Profile",
    "deal.save": "Save",
    "deal.whoTheyAre": "Who They Are",
    "deal.businessContext": "Business Context",
    "deal.relationshipStatus": "Relationship Status",
    "deal.engagement": "Engagement",
    "deal.lastInteraction": "Last interaction:",
    "deal.personalTalkingPoints": "Personal Talking Points",
    "deal.openActions": "Open Actions",
    "deal.dealContext": "Deal Context",
    "deal.stage": "Stage",
    "deal.confidence": "Confidence",
    "deal.acv": "ACV",
    "deal.situation": "Situation:",
    "deal.aiGeneratedBrief": "AI-Generated Brief",
    "deal.generating": "Generating...",
    "deal.regenerate": "Regenerate",
    "deal.generateBrief": "Generate Brief",
    "deal.generatingBriefFor": "Generating brief for",
    "deal.clickGenerateBrief": "Click \"Generate Brief\" to get an AI-crafted narrative brief based on all available context for",
    "deal.decisionStance": "Decision Stance",
    "deal.role": "Role",
    "deal.selectAll": "(select all that apply)",
    "deal.keyInsights": "Key Insights",
    "deal.knowYourStakeholder": "Know Your Stakeholder",
    "deal.aiSignals": "AI Signals",
    "deal.personalNotes": "Personal Notes",
    "deal.personalNotesPlaceholder": "Add personal context — hobbies, family mentions, communication style, things to remember before your next meeting...",
    "deal.addPersonalNotes": "+ Add personal notes about",
    "deal.contact": "Contact",
    "deal.relatedInteractions": "Related Interactions",
    "deal.noDirectInteractions": "No direct interactions recorded.",
    "deal.preMeetingBrief": "Pre-meeting Brief",
    // DealInsightPanel
    "insight.dealInsight": "Deal Insight",
    "insight.winConfidence": "Win Confidence",
    "insight.analyseDeal": "Analyse deal",
    "insight.analysing": "Analysing…",
    "insight.confidenceTrend": "Confidence Trend",
    "insight.insightsUpdated": "Insights updated from your conversation",
    "insight.whatsHappening": "What's Happening",
    "insight.keyRisks": "Key Risks",
    "insight.whatsNext": "What's Next",
    "insight.nextActions": "Next Actions",
    "insight.noActions": "No actions yet — click + to add",
    "insight.describeAction": "Describe the action...",
    "insight.add": "Add",
    "insight.overdue": "Overdue",
    "insight.due": "Due",
    "insight.chatPlaceholder": "Tell Meridian what changed, or ask why...",
    "insight.hideConversation": "Hide conversation",
    "insight.messages": "messages",
    "insight.message": "message",
    "insight.suggestedContacts": "Suggested Contacts",
    "insight.addedToMap": "Added to map",
    "insight.addToMap": "Add to Map",
    "insight.relevantStakeholders": "Relevant Stakeholders",
    "insight.accept": "Accept",
    "insight.dismiss": "Dismiss",
    "insight.later": "Later",
    "insight.addedToNextActions": "Added to Next Actions",
    "insight.savedForLater": "Saved for later",
    "insight.undo": "undo",
    "insight.refreshHint": "Hit \"Refresh Insights\" above to generate AI rationale for this action.",
    "insight.rerunHint": "Re-run Analyse Deal to generate detailed risk analysis.",
  },
  zh: {
    // Navigation
    "nav.dashboard": "仪表盘",
    "nav.deals": "销售管道",
    "nav.stakeholders": "利益相关方",
    "nav.transcripts": "Deal Room",
    "nav.knowledge": "知识库",
    "nav.ask": "问 Meridian",
    "nav.settings": "设置",
    "nav.signout": "退出登录",
    "nav.newDeal": "新建 Deal",
    // Settings page
    "settings.title": "设置",
    "settings.account": "账号",
    "settings.account.desc": "管理您的个人资料和偏好设置",
    "settings.language": "语言与地区",
    "settings.language.desc": "选择您的首选语言",
    "settings.team": "团队",
    "settings.team.desc": "邀请同事并管理团队访问权限",
    "settings.displayName": "显示名称",
    "settings.email": "邮箱",
    "settings.save": "保存更改",
    "settings.saved": "已保存",
    "settings.lang.en": "English",
    "settings.lang.zh": "中文 (Chinese)",
    "settings.invite.email": "邮箱地址",
    "settings.invite.send": "发送邀请",
    "settings.invite.sent": "邀请已发送！",
    "settings.invite.placeholder": "colleague@company.com",
    "settings.members": "团队成员",
    "settings.theme": "外观",
    "settings.theme.dark": "深色",
    "settings.theme.light": "浅色",
    // Dashboard
    "dashboard.greeting": "早上好",
    "dashboard.welcome": "欢迎使用 Meridian。创建您的第一个交易开始吧。",
    "dashboard.attention": "以下是今天需要您关注的事项。",
    "dashboard.totalPipeline": "总管线",
    "dashboard.predictableRevenue": "可预测收入",
    "dashboard.avgConfidence": "平均置信度",
    "dashboard.atRiskDeals": "风险交易",
    "dashboard.dealsNeedingAction": "需要行动的交易",
    "dashboard.allDeals": "所有交易",
    "dashboard.total": "总计",
    "dashboard.pipelineByStage": "按阶段分布",
    // Pipeline sidebar
    "pipeline.overview": "管线概览",
    "pipeline.searchDeals": "搜索交易...",
    "pipeline.noDeals": "暂无交易。",
    "pipeline.createFirst": "创建您的第一个交易",
    "pipeline.totalPipeline": "总管线",
    "pipeline.predictableRevenue": "可预测收入",
    "pipeline.newDeal": "新建交易",
    "pipeline.show": "显示管线",
    "pipeline.hide": "隐藏管线",
    // Deal detail
    "deal.lastEdited": "最后编辑于",
    "deal.ago": "前",
    "deal.updateHistory": "更新客户历史",
    "deal.buyingCommittee": "采购委员会",
    "deal.accountSignals": "客户信号",
    "deal.allInteractions": "所有互动",
    "deal.dealStrategy": "交易策略",
    "deal.dealInsight": "交易洞察",
    "deal.winConfidence": "赢单置信度",
    "deal.analyseDeal": "分析交易",
    "deal.whatsHappening": "当前动态",
    "deal.keyRisks": "关键风险",
    "deal.whatsNext": "下一步建议",
    "deal.nextActions": "待办事项",
    "deal.noActions": "暂无待办 — 点击 + 添加",
    "deal.interactions": "互动记录",
    "deal.noContact": "未联系",
    "deal.reportsTo": "汇报关系",
    "deal.influences": "影响关系",
    "deal.collaborates": "协作关系",
    "deal.blocks": "阻碍关系",
    "deal.positive": "正面",
    "deal.neutral": "中立",
    "deal.negative": "负面",
    "deal.heat": "热度 = 近14天接触点",
    "deal.view": "查看",
    "deal.edit": "编辑",
    "deal.addInteraction": "添加互动",
    // Stakeholder roles
    "role.champion": "内部支持者",
    "role.decisionMaker": "决策者",
    "role.influencer": "影响者",
    "role.blocker": "阻碍者",
    "role.evaluator": "评估者",
    "role.endUser": "终端用户",
    // Stages
    "stage.discovery": "需求发现",
    "stage.demo": "产品演示",
    "stage.technicalEvaluation": "技术评估",
    "stage.poc": "POC验证",
    "stage.negotiation": "商务谈判",
    "stage.closedWon": "赢单",
    "stage.closedLost": "丢单",
    // Common
    "common.cancel": "取消",
    "common.save": "保存",
    "common.loading": "加载中...",
    "common.back": "返回",
    "common.next": "下一步",
    "common.day": "天",
    "common.lightMode": "浅色模式",
    "common.darkMode": "深色模式",
    // Onboarding
    "onboarding.step1": "产品信息",
    "onboarding.step2": "销售流程",
    "onboarding.step3": "定义ICP",
    // DealDetail page
    "deal.loadingDeal": "加载交易中...",
    "deal.notFound": "未找到交易",
    "deal.backToDashboard": "返回仪表盘",
    "deal.companyOverview": "公司概览",
    "deal.happening": "动态：",
    "deal.next": "下一步：",
    "deal.risks": "风险：",
    "deal.interactionsRecorded": "条互动记录",
    "deal.interactionRecorded": "条互动记录",
    "deal.noInteractions": "暂无互动记录",
    "deal.addInteractionHint": "点击『添加互动』记录您的第一次接触",
    "deal.notesTranscript": "笔记 / 转录",
    "deal.meetingNotesPlaceholder": "会议笔记、关键决策、行动项...",
    "deal.done": "完成",
    "deal.delete": "删除",
    "deal.participantName": "参与者姓名",
    "deal.noNotesYet": "暂无笔记 — 点击编辑添加",
    "deal.collapseTranscript": "收起转录",
    "deal.viewFullTranscript": "查看完整转录",
    "deal.fullTranscript": "完整转录",
    "deal.fullNotes": "完整笔记",
    "deal.strategyTitle": "交易策略",
    "deal.strategyDesc": "此交易的内部策略笔记 — 价格灵活度、关系策略、竞争情报和内部协调。这些笔记将帮助 AI 代理优化建议。",
    "deal.addNote": "添加笔记",
    "deal.noStrategyNotes": "暂无策略笔记",
    "deal.strategyEmptyHint": "添加内部背景信息，如价格灵活度、战略优先级或关系策略 — AI 代理将据此定制建议。",
    "deal.addFirstNote": "添加第一条策略笔记",
    "deal.strategyPlaceholder": "描述此交易的内部策略、背景或约束条件...",
    "deal.emptyNote": "空笔记 — 点击编辑添加内容",
    // Strategy categories
    "strategy.pricing": "价格灵活度",
    "strategy.relationship": "关系策略",
    "strategy.competitive": "竞争情报",
    "strategy.internal": "内部协调",
    "strategy.other": "其他",
    // Stakeholder profile modal
    "deal.brief": "简报",
    "deal.profile": "档案",
    "deal.save": "保存",
    "deal.whoTheyAre": "人物概况",
    "deal.businessContext": "业务背景",
    "deal.relationshipStatus": "关系状态",
    "deal.engagement": "参与度",
    "deal.lastInteraction": "上次互动：",
    "deal.personalTalkingPoints": "个人话题要点",
    "deal.openActions": "待办事项",
    "deal.dealContext": "交易背景",
    "deal.stage": "阶段",
    "deal.confidence": "置信度",
    "deal.acv": "年合同额",
    "deal.situation": "当前情况：",
    "deal.aiGeneratedBrief": "AI 生成简报",
    "deal.generating": "生成中...",
    "deal.regenerate": "重新生成",
    "deal.generateBrief": "生成简报",
    "deal.generatingBriefFor": "正在为以下人员生成简报",
    "deal.clickGenerateBrief": "点击『生成简报』获取基于所有可用信息的 AI 叙事简报，对象：",
    "deal.decisionStance": "决策立场",
    "deal.role": "角色",
    "deal.selectAll": "（可多选）",
    "deal.keyInsights": "关键洞察",
    "deal.knowYourStakeholder": "了解您的利益相关方",
    "deal.aiSignals": "AI 信号",
    "deal.personalNotes": "个人笔记",
    "deal.personalNotesPlaceholder": "添加个人背景 — 爱好、家庭提及、沟通风格、下次会议前需记住的事项...",
    "deal.addPersonalNotes": "+ 添加个人笔记关于",
    "deal.contact": "联系方式",
    "deal.relatedInteractions": "相关互动",
    "deal.noDirectInteractions": "暂无直接互动记录。",
    "deal.preMeetingBrief": "会前简报",
    // DealInsightPanel
    "insight.dealInsight": "交易洞察",
    "insight.winConfidence": "赢单置信度",
    "insight.analyseDeal": "分析交易",
    "insight.analysing": "分析中…",
    "insight.confidenceTrend": "置信度趋势",
    "insight.insightsUpdated": "洞察已根据您的对话更新",
    "insight.whatsHappening": "当前动态",
    "insight.keyRisks": "关键风险",
    "insight.whatsNext": "下一步建议",
    "insight.nextActions": "待办事项",
    "insight.noActions": "暂无待办 — 点击 + 添加",
    "insight.describeAction": "描述行动...",
    "insight.add": "添加",
    "insight.overdue": "已逾期",
    "insight.due": "截止",
    "insight.chatPlaceholder": "告诉 Meridian 有什么变化，或问为什么...",
    "insight.hideConversation": "隐藏对话",
    "insight.messages": "条消息",
    "insight.message": "条消息",
    "insight.suggestedContacts": "建议联系人",
    "insight.addedToMap": "已添加到地图",
    "insight.addToMap": "添加到地图",
    "insight.relevantStakeholders": "相关利益方",
    "insight.accept": "接受",
    "insight.dismiss": "忽略",
    "insight.later": "稍后",
    "insight.addedToNextActions": "已添加到待办事项",
    "insight.savedForLater": "已保存待后续处理",
    "insight.undo": "撤销",
    "insight.refreshHint": "点击上方『刷新洞察』为此操作生成 AI 分析。",
    "insight.rerunHint": "重新运行『分析交易』以生成详细风险分析。",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("language") as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] ?? translations["en"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
